from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1312, 750)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("#button_backmenu{font-family:century gothic;font-size:18px;background:rgba(170, 170, 131,0.6);border-radius:15px;}#button_backmenu:hover{background-color: rgb(135, 124, 255);}\n"
"#button_dothi , #button_htluong , #button_tslgiac , #button_hept , #button_ptb2,#button_gtgv{font-family:century gothic;font-size:22px;font-weight: bold;background:rgba(0, 255, 255, 0.8);border-radius:20px;}\n"
"#button_dothi:hover  , #button_htluong:hover  , #button_tslgiac:hover  , #button_hept:hover  , #button_ptb2:hover ,  #button_ptb1:hover,#button_gtgv:hover {background-color: rgb(18, 23, 39);color: rgb(0, 255, 255);}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_backmenu = QtWidgets.QPushButton(self.centralwidget)
        self.button_backmenu.setGeometry(QtCore.QRect(40, 30, 161, 51))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.button_backmenu.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/.icon_back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_backmenu.setIcon(icon)
        self.button_backmenu.setIconSize(QtCore.QSize(35, 35))
        self.button_backmenu.setObjectName("button_backmenu")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(130, 120, 1131, 471))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.button_tslgiac = QtWidgets.QPushButton(self.frame)
        self.button_tslgiac.setGeometry(QtCore.QRect(750, 50, 231, 131))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_tslgiac.setFont(font)
        self.button_tslgiac.setObjectName("button_tslgiac")
        self.button_gtgv = QtWidgets.QPushButton(self.frame)
        self.button_gtgv.setGeometry(QtCore.QRect(70, 260, 241, 131))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_gtgv.setFont(font)
        self.button_gtgv.setObjectName("button_gtgv")
        self.button_dothi = QtWidgets.QPushButton(self.frame)
        self.button_dothi.setGeometry(QtCore.QRect(70, 50, 241, 131))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_dothi.setFont(font)
        self.button_dothi.setStyleSheet("")
        self.button_dothi.setObjectName("button_dothi")
        self.button_htluong = QtWidgets.QPushButton(self.frame)
        self.button_htluong.setGeometry(QtCore.QRect(410, 50, 241, 131))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_htluong.setFont(font)
        self.button_htluong.setStyleSheet("")
        self.button_htluong.setObjectName("button_htluong")
        self.button_ptb2 = QtWidgets.QPushButton(self.frame)
        self.button_ptb2.setGeometry(QtCore.QRect(410, 260, 241, 131))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_ptb2.setFont(font)
        self.button_ptb2.setObjectName("button_ptb2")
        self.button_hept = QtWidgets.QPushButton(self.frame)
        self.button_hept.setGeometry(QtCore.QRect(750, 260, 231, 131))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_hept.setFont(font)
        self.button_hept.setObjectName("button_hept")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 640, 591, 51))
        self.label_4.setObjectName("label_4")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1020, 10, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1312, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Menu"))
        self.button_backmenu.setText(_translate("MainWindow", "Back"))
        self.button_tslgiac.setText(_translate("MainWindow", "Tỉ Số Lượng Giác"))
        self.button_gtgv.setText(_translate("MainWindow", "Giải Tam Giác Vuông"))
        self.button_dothi.setText(_translate("MainWindow", "Vẽ Đồ Thị Hàm Số"))
        self.button_htluong.setText(_translate("MainWindow", "Hệ Thức Lượng"))
        self.button_ptb2.setText(_translate("MainWindow", "Phương Trình Bậc 2"))
        self.button_hept.setText(_translate("MainWindow", "Hệ Phương Trình"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#ff0000;\">Báo Cáo Lỗi: trongtuan150409@gmail.com</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">dev: Nguyen Trong Tuan</span></p></body></html>"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
