from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1312, 750)
        MainWindow.setStyleSheet("#button_back_ptb2{font-family:century gothic;font-size:18px;background:rgba(170, 170, 131,0.6);border-radius:15px;}\n"
"#button_back_ptb2:hover{background-color: rgb(135, 124, 255);}\n"
"#frame_2{background:#333;border-radius:30px;}\n"
"#out_sln ,#out_x1 , #out_x2 , #out_delta , #out_s , #out_p{background:transparent;border:none;color:rgb(0, 85, 255);border-bottom:1px solid #717072;font-size: 23px;}\n"
"#out_sln:hover ,#out_x1:hover , #out_x2:hover , #out_delta:hover , #out_s:hover , #out_p:hover{border-bottom:1px solid rgb(0, 255, 255);}\n"
"#inp_a , #inp_b , #inp_c{background:transparent;border:none;color:rgb(255, 97, 255);border-bottom:1px solid #717072;font-size: 23px;}\n"
"#button_enter_ptb2{background:rgb(80, 255, 130);border-radius:15px;}\n"
"#button_enter_ptb2:hover{background-color: rgb(0, 255, 0);}\n"
"#fa{background:rgb(0, 255, 255);border-radius:30px;}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 20, 601, 31))
        self.label.setObjectName("label")
        self.fa = QtWidgets.QFrame(self.centralwidget)
        self.fa.setGeometry(QtCore.QRect(340, 100, 701, 111))
        self.fa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fa.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fa.setObjectName("fa")
        self.inp_a = QtWidgets.QLineEdit(self.fa)
        self.inp_a.setGeometry(QtCore.QRect(30, 59, 141, 31))
        self.inp_a.setText("")
        self.inp_a.setObjectName("inp_a")
        self.label_2 = QtWidgets.QLabel(self.fa)
        self.label_2.setGeometry(QtCore.QRect(190, 60, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.inp_b = QtWidgets.QLineEdit(self.fa)
        self.inp_b.setGeometry(QtCore.QRect(260, 58, 113, 31))
        self.inp_b.setText("")
        self.inp_b.setObjectName("inp_b")
        self.label_3 = QtWidgets.QLabel(self.fa)
        self.label_3.setGeometry(QtCore.QRect(390, 60, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.inp_c = QtWidgets.QLineEdit(self.fa)
        self.inp_c.setGeometry(QtCore.QRect(440, 59, 131, 31))
        self.inp_c.setObjectName("inp_c")
        self.label_4 = QtWidgets.QLabel(self.fa)
        self.label_4.setGeometry(QtCore.QRect(580, 60, 47, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.fa)
        self.label_10.setGeometry(QtCore.QRect(30, 10, 411, 31))
        self.label_10.setObjectName("label_10")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(390, 290, 631, 371))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.out_sln = QtWidgets.QLineEdit(self.frame_2)
        self.out_sln.setGeometry(QtCore.QRect(80, 20, 451, 31))
        self.out_sln.setText("")
        self.out_sln.setObjectName("out_sln")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(40, 60, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.out_x1 = QtWidgets.QLineEdit(self.frame_2)
        self.out_x1.setGeometry(QtCore.QRect(150, 100, 391, 31))
        self.out_x1.setText("")
        self.out_x1.setObjectName("out_x1")
        self.out_x2 = QtWidgets.QLineEdit(self.frame_2)
        self.out_x2.setGeometry(QtCore.QRect(150, 140, 391, 31))
        self.out_x2.setObjectName("out_x2")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(40, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.out_delta = QtWidgets.QLineEdit(self.frame_2)
        self.out_delta.setGeometry(QtCore.QRect(130, 180, 411, 31))
        self.out_delta.setObjectName("out_delta")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(40, 240, 91, 31))
        self.label_7.setObjectName("label_7")
        self.out_s = QtWidgets.QLineEdit(self.frame_2)
        self.out_s.setGeometry(QtCore.QRect(130, 240, 411, 31))
        self.out_s.setObjectName("out_s")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(40, 300, 111, 31))
        self.label_8.setObjectName("label_8")
        self.out_p = QtWidgets.QLineEdit(self.frame_2)
        self.out_p.setGeometry(QtCore.QRect(130, 300, 411, 31))
        self.out_p.setObjectName("out_p")
        self.button_back_ptb2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_back_ptb2.setGeometry(QtCore.QRect(40, 30, 161, 51))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.button_back_ptb2.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/.icon_back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_back_ptb2.setIcon(icon)
        self.button_back_ptb2.setIconSize(QtCore.QSize(35, 35))
        self.button_back_ptb2.setObjectName("button_back_ptb2")
        self.button_enter_ptb2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_enter_ptb2.setGeometry(QtCore.QRect(140, 420, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_enter_ptb2.setFont(font)
        self.button_enter_ptb2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/.icon_enter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_enter_ptb2.setIcon(icon1)
        self.button_enter_ptb2.setIconSize(QtCore.QSize(60, 60))
        self.button_enter_ptb2.setObjectName("button_enter_ptb2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1020, 10, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1312, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.button_enter_ptb2.clicked.connect(self.ptb2)

    def ptb2(self):
        import math
        a=float(self.inp_a.text())
        b=float(self.inp_b.text())
        c=float(self.inp_c.text())
        ptvn="Phương Trình Vô Nghiệm"
        ptcnk="Phương Trình Có Nghiệm Kép"
        ptcnpb="Phương Trình Có 2 Nghiệm Phân Biệt"
        er="Lỗi!! Hãy Xem Lại Các Hệ Số"
        delta=b**2-4*a*c
        self.out_delta.setText(str(delta))
        if a==0:
            self.out_sln.setText(str(er))
        elif delta<0:
            self.out_sln.setText(str(ptvn))
            self.out_s.setText("")
            self.out_p.setText("")
            self.out_x1.setText("")
            self.out_x2.setText("")
        elif delta==0:
            kq1=-b/2*a
            self.out_sln.setText(str(ptcnk))
            self.out_x1.setText(str(kq1))
            self.out_x2.setText(str(kq1))
            s=float(float(kq1))+(float(kq1))
            p=float((kq1)*float(kq1))
            self.out_s.setText(str(s))
            self.out_p.setText(str(p))
        elif delta>0:
            kqx1=(-b+math.sqrt(delta))/(2*a)
            kqx2=(-b-math.sqrt(delta))/(a*a)
            self.out_sln.setText(str(ptcnpb))
            self.out_x1.setText(str(kqx1))
            self.out_x2.setText(str(kqx2))
            s=float(float(kqx1))+(float(kqx2))
            p=float((kqx1)*float(kqx2))
            self.out_s.setText(str(s))
            self.out_p.setText(str(p))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Giải Phương Trình Bậc 2"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Giải Phương Trình Bậc 2 (ax</span><span style=\" font-size:16pt; font-weight:600; vertical-align:super;\">2</span><span style=\" font-size:16pt; font-weight:600;\">+bx+c=0): </span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>x<span style=\" vertical-align:super;\">2</span> +</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "x +"))
        self.label_4.setText(_translate("MainWindow", "= 0"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#0000ff;\">Nhập Các Hệ Số Của Phương Trình: </span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#55ff00;\">Kết Quả (x</span><span style=\" color:#55ff00; vertical-align:sub;\">1</span><span style=\" color:#55ff00;\">, x</span><span style=\" color:#55ff00; vertical-align:sub;\">2</span><span style=\" color:#55ff00;\">)</span><span style=\" color:#55ff00;\">:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#55ff00;\">delta=</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#55ff00;\">Tổng S=</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#55ff00;\">Tích P=</span></p></body></html>"))
        self.button_back_ptb2.setText(_translate("MainWindow", "Back"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">dev: Nguyen Trong Tuan</span></p></body></html>"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
