from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1312, 750)
        MainWindow.setStyleSheet("#button_back_dths{font-family:century gothic;font-size:18px;background:rgba(170, 170, 131,0.6);border-radius:15px;}\n"
"#button_back_dths:hover,#cachve:hover,#cachve_2:hover{background-color: rgb(135, 124, 255);}\n"
"#frame{background:#333;border-radius:40px;}\n"
"#ex , #ex1{background:rgb(0, 255, 255);border-radius:50px;}\n"
"#ex:hover , #ex1:hover{background-color:rgb(0, 170, 255);}\n"
"#button_draw{background:rgb(80, 255, 130);border-radius:30px;}\n"
"#button_draw:hover{background-color: rgb(0, 255, 0);}\n"
"#frame_2{background:#333;border-radius:40px;}\n"
"#inp_hsa1 , #inp_hsa_2 , #inp_hsa_3 , #inp_hsb1 , #inp_hsb_2 , #inp_hsb_3 , #inp_hsa_b2_1 , #inp_hsa_b2_2,  #inp_hsa_b2_3{background:transparent;border:none;color:rgb(85, 255, 127);border-bottom:1px solid #717072;font-size: 24px;}\n"
"#inp_hsa1:hover , #inp_hsa_2:hover , #inp_hsa_3:hover , #inp_hsb1:hover , #inp_hsb_2:hover , #inp_hsb_3:hover , #inp_hsa_b2_1:hover , #inp_hsa_b2_2:hover,  #inp_hsa_b2_3:hover\n"
"{border-bottom:1px solid rgb(0, 255, 255);}\n"
"#cachve , #cachve_2{font-family:century gothic;font-size:25px;background:rgba(170, 170, 131,0.6);border-radius:15px;}\n"
"#tber{font-size:18px;}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(450, 50, 521, 41))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.button_draw = QtWidgets.QPushButton(self.centralwidget)
        self.button_draw.setGeometry(QtCore.QRect(530, 620, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_draw.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/.icon_draw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_draw.setIcon(icon)
        self.button_draw.setIconSize(QtCore.QSize(65, 65))
        self.button_draw.setObjectName("button_draw")
        self.button_back_dths = QtWidgets.QPushButton(self.centralwidget)
        self.button_back_dths.setGeometry(QtCore.QRect(40, 30, 161, 51))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.button_back_dths.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/.icon_back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_back_dths.setIcon(icon1)
        self.button_back_dths.setIconSize(QtCore.QSize(35, 35))
        self.button_back_dths.setObjectName("button_back_dths")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1020, 10, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(720, 169, 481, 381))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.box_b2_2 = QtWidgets.QGroupBox(self.frame)
        self.box_b2_2.setGeometry(QtCore.QRect(100, 177, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.box_b2_2.setFont(font)
        self.box_b2_2.setTitle("")
        self.box_b2_2.setObjectName("box_b2_2")
        self.label_14 = QtWidgets.QLabel(self.box_b2_2)
        self.label_14.setGeometry(QtCore.QRect(20, 0, 47, 31))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.box_b2_2)
        self.label_15.setGeometry(QtCore.QRect(200, 0, 47, 31))
        self.label_15.setObjectName("label_15")
        self.inp_hsa_b2_2 = QtWidgets.QLineEdit(self.box_b2_2)
        self.inp_hsa_b2_2.setGeometry(QtCore.QRect(52, 0, 131, 31))
        self.inp_hsa_b2_2.setText("")
        self.inp_hsa_b2_2.setObjectName("inp_hsa_b2_2")
        self.box_b2 = QtWidgets.QGroupBox(self.frame)
        self.box_b2.setGeometry(QtCore.QRect(100, 97, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.box_b2.setFont(font)
        self.box_b2.setTitle("")
        self.box_b2.setObjectName("box_b2")
        self.label_6 = QtWidgets.QLabel(self.box_b2)
        self.label_6.setGeometry(QtCore.QRect(20, 0, 47, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.box_b2)
        self.label_7.setGeometry(QtCore.QRect(200, 0, 47, 31))
        self.label_7.setObjectName("label_7")
        self.inp_hsa_b2_1 = QtWidgets.QLineEdit(self.box_b2)
        self.inp_hsa_b2_1.setGeometry(QtCore.QRect(50, 0, 131, 31))
        self.inp_hsa_b2_1.setStyleSheet("")
        self.inp_hsa_b2_1.setText("")
        self.inp_hsa_b2_1.setObjectName("inp_hsa_b2_1")
        self.box_b2_3 = QtWidgets.QGroupBox(self.frame)
        self.box_b2_3.setGeometry(QtCore.QRect(100, 257, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.box_b2_3.setFont(font)
        self.box_b2_3.setTitle("")
        self.box_b2_3.setObjectName("box_b2_3")
        self.label_16 = QtWidgets.QLabel(self.box_b2_3)
        self.label_16.setGeometry(QtCore.QRect(20, 0, 47, 31))
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.box_b2_3)
        self.label_17.setGeometry(QtCore.QRect(200, 0, 47, 31))
        self.label_17.setObjectName("label_17")
        self.inp_hsa_b2_3 = QtWidgets.QLineEdit(self.box_b2_3)
        self.inp_hsa_b2_3.setGeometry(QtCore.QRect(52, -1, 131, 31))
        self.inp_hsa_b2_3.setText("")
        self.inp_hsa_b2_3.setObjectName("inp_hsa_b2_3")
        self.cachve_2 = QtWidgets.QPushButton(self.frame)
        self.cachve_2.setGeometry(QtCore.QRect(156, 320, 161, 51))
        self.cachve_2.setObjectName("cachve_2")
        self.ex = QtWidgets.QPushButton(self.centralwidget)
        self.ex.setGeometry(QtCore.QRect(880, 110, 181, 111))
        self.ex.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picture/.icon_parabol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ex.setIcon(icon2)
        self.ex.setIconSize(QtCore.QSize(150, 150))
        self.ex.setObjectName("ex")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(130, 169, 461, 381))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.box_b1 = QtWidgets.QGroupBox(self.frame_2)
        self.box_b1.setGeometry(QtCore.QRect(40, 100, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.box_b1.setFont(font)
        self.box_b1.setTitle("")
        self.box_b1.setObjectName("box_b1")
        self.label_4 = QtWidgets.QLabel(self.box_b1)
        self.label_4.setGeometry(QtCore.QRect(20, 0, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.box_b1)
        self.label_5.setGeometry(QtCore.QRect(180, 0, 47, 31))
        self.label_5.setObjectName("label_5")
        self.inp_hsa1 = QtWidgets.QLineEdit(self.box_b1)
        self.inp_hsa1.setGeometry(QtCore.QRect(60, -1, 113, 31))
        self.inp_hsa1.setText("")
        self.inp_hsa1.setObjectName("inp_hsa1")
        self.inp_hsb1 = QtWidgets.QLineEdit(self.box_b1)
        self.inp_hsb1.setGeometry(QtCore.QRect(220, -1, 113, 31))
        self.inp_hsb1.setText("")
        self.inp_hsb1.setObjectName("inp_hsb1")
        self.box_b1_2 = QtWidgets.QGroupBox(self.frame_2)
        self.box_b1_2.setGeometry(QtCore.QRect(40, 180, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.box_b1_2.setFont(font)
        self.box_b1_2.setTitle("")
        self.box_b1_2.setObjectName("box_b1_2")
        self.label_8 = QtWidgets.QLabel(self.box_b1_2)
        self.label_8.setGeometry(QtCore.QRect(20, 0, 47, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.box_b1_2)
        self.label_9.setGeometry(QtCore.QRect(180, 0, 47, 31))
        self.label_9.setObjectName("label_9")
        self.inp_hsa_2 = QtWidgets.QLineEdit(self.box_b1_2)
        self.inp_hsa_2.setGeometry(QtCore.QRect(60, -1, 113, 31))
        self.inp_hsa_2.setText("")
        self.inp_hsa_2.setObjectName("inp_hsa_2")
        self.inp_hsb_2 = QtWidgets.QLineEdit(self.box_b1_2)
        self.inp_hsb_2.setGeometry(QtCore.QRect(220, -1, 113, 31))
        self.inp_hsb_2.setText("")
        self.inp_hsb_2.setObjectName("inp_hsb_2")
        self.box_b1_3 = QtWidgets.QGroupBox(self.frame_2)
        self.box_b1_3.setGeometry(QtCore.QRect(40, 260, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.box_b1_3.setFont(font)
        self.box_b1_3.setTitle("")
        self.box_b1_3.setObjectName("box_b1_3")
        self.label_10 = QtWidgets.QLabel(self.box_b1_3)
        self.label_10.setGeometry(QtCore.QRect(20, 0, 47, 31))
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.box_b1_3)
        self.label_11.setGeometry(QtCore.QRect(180, 0, 47, 31))
        self.label_11.setObjectName("label_11")
        self.inp_hsa_3 = QtWidgets.QLineEdit(self.box_b1_3)
        self.inp_hsa_3.setGeometry(QtCore.QRect(60, -1, 113, 31))
        self.inp_hsa_3.setText("")
        self.inp_hsa_3.setObjectName("inp_hsa_3")
        self.inp_hsb_3 = QtWidgets.QLineEdit(self.box_b1_3)
        self.inp_hsb_3.setGeometry(QtCore.QRect(220, -1, 113, 31))
        self.inp_hsb_3.setText("")
        self.inp_hsb_3.setObjectName("inp_hsb_3")
        self.cachve = QtWidgets.QPushButton(self.frame_2)
        self.cachve.setGeometry(QtCore.QRect(150, 320, 161, 51))
        self.cachve.setObjectName("cachve")
        self.ex1 = QtWidgets.QPushButton(self.centralwidget)
        self.ex1.setGeometry(QtCore.QRect(270, 120, 191, 111))
        self.ex1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/picture/.icon_dtb1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ex1.setIcon(icon3)
        self.ex1.setIconSize(QtCore.QSize(110, 110))
        self.ex1.setObjectName("ex1")
        self.tber = QtWidgets.QLineEdit(self.centralwidget)
        self.tber.setGeometry(QtCore.QRect(10, 691, 511, 31))
        self.tber.setText("")
        self.tber.setObjectName("tber")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1312, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.button_draw.clicked.connect(self.dths)

    def dths(self):
        from matplotlib.pyplot import figure , plot, xlabel ,ylabel, show, axhline , axvline , grid , xticks , yticks , xlim , ylim , legend , title
        from numpy import arange
        import colorama
        colorama.init()
        fig= figure()
        fig.set_facecolor("black")
        ax = fig.add_subplot(111)
        ax.set_facecolor("black")
        try:
            if self.inp_hsa1.isModified() and self.inp_hsb1.isModified():
                hsa1=float(self.inp_hsa1.text())
                hsb1=float(self.inp_hsb1.text())
                x = arange(-10, 10, 0.01)
                y1=hsa1*x+hsb1
                plot(x, y1)
            if self.inp_hsa_2.isModified() and self.inp_hsb_2.isModified():
                hsa2=float(self.inp_hsa_2.text())
                hsb2=float(self.inp_hsb_2.text())
                x = arange(-10, 10, 0.01)
                y2=hsa2*x+hsb2
                plot(x, y2)
            if self.inp_hsa_3.isModified() and self.inp_hsb_3.isModified():
                hsa3=float(self.inp_hsa_3.text())
                hsb3=float(self.inp_hsb_3.text())
                x = arange(-10, 10, 0.01)
                y3=hsa3*x+hsb3
                plot(x, y3)
            if self.inp_hsa_b2_1.isModified() :
                hsb2_1=float(self.inp_hsa_b2_1.text())
                x = arange(-10, 10, 0.01)
                y11=hsb2_1*x**2
                plot(x, y11)
            if self.inp_hsa_b2_2.isModified() :
                hsb2_2=float(self.inp_hsa_b2_2.text())
                x = arange(-10, 10, 0.01)
                y12=hsb2_2*x**2
                plot(x, y12)
            if self.inp_hsa_b2_3.isModified() :
                hsb2_3=float(self.inp_hsa_b2_3.text())
                x = arange(-10, 10, 0.01)
                y13=hsb2_3*x**2
                plot(x, y13)

            # Thêm trục x và trục y cho đồ thị
            xlabel("y", color='white')
            ylabel("x", color='white')
            axhline(y=0, color='white')
            axvline(x=0, color='white')
            plot([0, 1], [0, 0], color='white')
            plot([0, -1], [0, 0], color='white')
            grid(True, which="both", axis="both", color='white', linewidth=1, alpha=0.2)
            xticks(arange(-51, 51, 1), color='white', size=8)
            yticks(arange(-51, 51, 1),color='white', size=8)
            xlim(-12,12)
            ylim(-12,12)
            legend()
            title("created by: \n Nguyễn Trọng Tuấn " , fontsize = 8, loc="right", color = 'white')
            show()
        except: self.tber.setText(str("Nếu lỗi hãy thoát ra vô lại màn hình. Xin lỗi vì sự bất tiện này"))


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vẽ đồ thị hàm số"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#0055ff;\">Vẽ Đồ Thị Hàm Số y=ax+b và y=ax</span><span style=\" font-size:16pt; font-weight:600; color:#0055ff; vertical-align:super;\">2</span><span style=\" font-size:16pt; font-weight:600; color:#0055ff;\">: </span></p></body></html>"))
        self.button_draw.setText(_translate("MainWindow", "Vẽ"))
        self.button_back_dths.setText(_translate("MainWindow", "Back"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">dev: Nguyen Trong Tuan</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00ff00;\">y=</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00ff00;\">x</span><span style=\" font-size:14pt; color:#00ff00; vertical-align:super;\">2</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00ff00;\">y=</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00ff00;\">x</span><span style=\" font-size:14pt; color:#00ff00; vertical-align:super;\">2</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00ff00;\">y=</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00ff00;\">x</span><span style=\" font-size:14pt; color:#00ff00; vertical-align:super;\">2</span></p></body></html>"))
        self.cachve_2.setText(_translate("MainWindow", "Cách Vẽ"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00aaff;\">y=</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00aaff;\">x+</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00aaff;\">y=</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00aaff;\">x+</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00aaff;\">y=</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00aaff;\">x+</span></p></body></html>"))
        self.cachve.setText(_translate("MainWindow", "Cách Vẽ"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
