from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1312, 750)
        MainWindow.setStyleSheet("#button_back_hpt{font-family:century gothic;font-size:18px;background:rgba(170, 170, 131,0.6);border-radius:15px;}\n"
"#button_back_hpt:hover{background-color: rgb(135, 124, 255);}\n"
"#ngoac{background-color: rgba(255, 255, 255,0.001);border-radius:20px;}\n"
"#button_enter_hpt{background:rgba(170, 255, 255,0.8);border-radius:15px;}\n"
"#button_enter_hpt:hover{background:rgb(0, 170, 255);border-radius:10px;}\n"
"#inp_a_2 , #inp_b_2 , #inp_c_2,#inp_ap_2 , #inp_bp_2 , #inp_cp_2 , #out_kqx , #out_kqy{font-size:24px;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(150, 59, 1031, 591))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(70, 80, 851, 211))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(490, 110, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.inp_b_2 = QtWidgets.QLineEdit(self.groupBox)
        self.inp_b_2.setGeometry(QtCore.QRect(320, 34, 151, 31))
        self.inp_b_2.setText("")
        self.inp_b_2.setObjectName("inp_b_2")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(260, 35, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(490, 30, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.inp_cp_2 = QtWidgets.QLineEdit(self.groupBox)
        self.inp_cp_2.setGeometry(QtCore.QRect(550, 119, 151, 31))
        self.inp_cp_2.setText("")
        self.inp_cp_2.setObjectName("inp_cp_2")
        self.inp_bp_2 = QtWidgets.QLineEdit(self.groupBox)
        self.inp_bp_2.setGeometry(QtCore.QRect(320, 119, 151, 31))
        self.inp_bp_2.setText("")
        self.inp_bp_2.setObjectName("inp_bp_2")
        self.inp_a_2 = QtWidgets.QLineEdit(self.groupBox)
        self.inp_a_2.setGeometry(QtCore.QRect(90, 30, 151, 31))
        self.inp_a_2.setText("")
        self.inp_a_2.setObjectName("inp_a_2")
        self.inp_ap_2 = QtWidgets.QLineEdit(self.groupBox)
        self.inp_ap_2.setGeometry(QtCore.QRect(90, 119, 151, 31))
        self.inp_ap_2.setText("")
        self.inp_ap_2.setObjectName("inp_ap_2")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(260, 120, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.inp_c_2 = QtWidgets.QLineEdit(self.groupBox)
        self.inp_c_2.setGeometry(QtCore.QRect(540, 34, 161, 31))
        self.inp_c_2.setText("")
        self.inp_c_2.setObjectName("inp_c_2")
        self.ngoac = QtWidgets.QPushButton(self.groupBox)
        self.ngoac.setGeometry(QtCore.QRect(40, -30, 51, 241))
        self.ngoac.setLocale(QtCore.QLocale(QtCore.QLocale.Ewe, QtCore.QLocale.Ghana))
        self.ngoac.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/.icon_nnhon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ngoac.setIcon(icon)
        self.ngoac.setIconSize(QtCore.QSize(100, 110))
        self.ngoac.setObjectName("ngoac")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(180, 400, 631, 141))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(16)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.out_kqx = QtWidgets.QLineEdit(self.groupBox_2)
        self.out_kqx.setGeometry(QtCore.QRect(180, 30, 371, 31))
        self.out_kqx.setText("")
        self.out_kqx.setObjectName("out_kqx")
        self.out_kqy = QtWidgets.QLineEdit(self.groupBox_2)
        self.out_kqy.setGeometry(QtCore.QRect(180, 80, 371, 31))
        self.out_kqy.setText("")
        self.out_kqy.setObjectName("out_kqy")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(130, 28, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(130, 75, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.button_enter_hpt = QtWidgets.QPushButton(self.frame)
        self.button_enter_hpt.setGeometry(QtCore.QRect(370, 300, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_enter_hpt.setFont(font)
        self.button_enter_hpt.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/.icon_enter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_enter_hpt.setIcon(icon1)
        self.button_enter_hpt.setIconSize(QtCore.QSize(99, 99))
        self.button_enter_hpt.setObjectName("button_enter_hpt")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(180, 0, 541, 41))
        self.label_2.setObjectName("label_2")
        self.button_back_hpt = QtWidgets.QPushButton(self.centralwidget)
        self.button_back_hpt.setGeometry(QtCore.QRect(40, 30, 161, 51))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.button_back_hpt.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picture/.icon_back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_back_hpt.setIcon(icon2)
        self.button_back_hpt.setIconSize(QtCore.QSize(35, 35))
        self.button_back_hpt.setObjectName("button_back_hpt")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(1020, 10, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1312, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.button_enter_hpt.clicked.connect(self.hpt)

    def hpt(self):
        a=float(self.inp_a_2.text())
        b=float(self.inp_b_2.text())
        c=float(self.inp_c_2.text())
        a1=float(self.inp_ap_2.text())
        b1=float(self.inp_bp_2.text())
        c1=float(self.inp_cp_2.text()) 
        ptvsn="Phương Trình Có Vô Số Nghiệm"
        ptvn="Phương Trình Vô Nghiệm"
        if ((a/a1) == (b/b1)) and ((b/b1) == (c/c1)) : 
            self.out_kqx.setText(str(ptvsn))
            self.out_kqy.setText(str(ptvsn))
        if ((a/a1) == (b/b1)) and ((b/b1) != (c/c1)) : 
            self.out_kqx.setText(str(ptvn))
            self.out_kqy.setText(str(ptvn))
        if (a/a1) != (b/b1) :
            y = (a * c1 - a1 * c) / (-a1 * b + a * b1)
            x = (c - b * y) / a
            self.out_kqx.setText(str(x))
            self.out_kqy.setText(str(y))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Giải Hệ Phương Trình"))
        self.label_12.setText(_translate("MainWindow", "y="))
        self.label_13.setText(_translate("MainWindow", "x+"))
        self.label_14.setText(_translate("MainWindow", "y="))
        self.label_15.setText(_translate("MainWindow", "x+"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Kết Quả"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">x=</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">y=</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#0055ff;\">Giải Hệ Phương Trình Bậc Nhất 2 Ẩn:</span></p></body></html>"))
        self.button_back_hpt.setText(_translate("MainWindow", "Back"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">dev: Nguyen Trong Tuan</span></p></body></html>"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
