from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(588, 316)
        Dialog.setStyleSheet("#gta , #gtb , #hsdt  , #x1 , #x2 , #y1 , #y2{font-size:24px}")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(180, 160, 381, 141))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(150, 0, 20, 131))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(10, 60, 361, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setGeometry(QtCore.QRect(10, 120, 361, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setGeometry(QtCore.QRect(10, 0, 361, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.groupBox)
        self.line_5.setGeometry(QtCore.QRect(0, 7, 16, 121))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.groupBox)
        self.line_6.setGeometry(QtCore.QRect(362, 7, 16, 121))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_34 = QtWidgets.QFrame(self.groupBox)
        self.line_34.setGeometry(QtCore.QRect(260, 0, 20, 131))
        self.line_34.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.hsdt = QtWidgets.QLineEdit(self.groupBox)
        self.hsdt.setGeometry(QtCore.QRect(30, 87, 113, 31))
        self.hsdt.setText("")
        self.hsdt.setObjectName("hsdt")
        self.x1 = QtWidgets.QLineEdit(self.groupBox)
        self.x1.setGeometry(QtCore.QRect(174, 30, 81, 31))
        self.x1.setText("")
        self.x1.setObjectName("x1")
        self.x2 = QtWidgets.QLineEdit(self.groupBox)
        self.x2.setGeometry(QtCore.QRect(280, 30, 81, 31))
        self.x2.setText("")
        self.x2.setObjectName("x2")
        self.y1 = QtWidgets.QLineEdit(self.groupBox)
        self.y1.setGeometry(QtCore.QRect(175, 89, 81, 31))
        self.y1.setText("")
        self.y1.setObjectName("y1")
        self.y2 = QtWidgets.QLineEdit(self.groupBox)
        self.y2.setGeometry(QtCore.QRect(281, 89, 81, 31))
        self.y2.setText("")
        self.y2.setObjectName("y2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(70, 20, 31, 31))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(19, 153, 171, 31))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(19, 117, 131, 31))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(150, 0, 391, 61))
        self.label_3.setObjectName("label_3")
        self.bgt_1 = QtWidgets.QPushButton(Dialog)
        self.bgt_1.setGeometry(QtCore.QRect(30, 200, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bgt_1.setFont(font)
        self.bgt_1.setAutoRepeat(True)
        self.bgt_1.setObjectName("bgt_1")
        self.gta = QtWidgets.QLineEdit(Dialog)
        self.gta.setGeometry(QtCore.QRect(260, 65, 81, 31))
        self.gta.setText("")
        self.gta.setObjectName("gta")
        self.gtb = QtWidgets.QLineEdit(Dialog)
        self.gtb.setGeometry(QtCore.QRect(394, 65, 81, 31))
        self.gtb.setText("")
        self.gtb.setObjectName("gtb")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(210, 60, 41, 41))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(347, 63, 41, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 191, 41))
        self.label_7.setObjectName("label_7")
        self.line_7 = QtWidgets.QFrame(Dialog)
        self.line_7.setGeometry(QtCore.QRect(10, 100, 561, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.bgt_1.clicked.connect(self.dt)
        
    def dt(self):
        a=float(self.gta.text())
        b=float(self.gtb.text())
        self.hsdt.setText(str("y=") + str(self.gta.text()) + str("x+") + str(self.gtb.text()))

        if b>0 or b<0:
            self.x1.setText(str("0"))
            self.y2.setText(str("0"))
            self.y1.setText(self.gtb.text())
            x2=float(-b/a)
            self.x2.setText((f"{round(x2, 2):.2f}"))

        if b==0:
            self.x1.setText(str("0"))
            self.x2.setText(str("1"))
            self.y1.setText(str("0"))
            
            self.y2.setText(str(self.gta.text()))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cách lập bảng giá trị y=ax+b"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt;\">x</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Bảng Giá Trị:</span></p><p><br/></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">TXĐ: R</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt;\">Cách Tạo Lập Bảng Giá Trị:</span></p></body></html>"))
        self.bgt_1.setText(_translate("Dialog", "Enter"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt;\">y=</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt;\">x+</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Nhập Các Giá Trị:</span></p></body></html>"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
